### ISSUE TITLE
CAN Open Eds has a different flavour

### ISSUE THREAD

**Issue by tkucic** [omidbimo/eds_pie#1]
Hi,
it seems the CAN Open EDS files have a different flavor. The separator is a new line.

This EDS fails on Exception: eds_pie.lexer:> ERROR! Concatenating these literals is not allowed. (Henrik)<IDENTIFIER> + (Lynggaard)<IDENTIFIER> @([idx:    28, ln:    2, col:  18] IDENTIFIER  "Lynggaard")

Test EDS File
[test.txt](https://github.com/omidbimo/eds_pie/files/7852554/test.txt)

**Comment by omidbimo** [comment]
Hi,
Sorry for the late answer.
You're right, I wrote the parser based on the ODVA documentation and the EDS format supported by the ODVA protocols seems to be different from CAN Open's!
Also, the EZ-EDS(ODVA's official software) can not parse your EDS file.
The parser is not suitable for parsing CAN Open EDSs.
